//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dictTeams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dictTeams()
        {
            this.dictTeamsPlayers = new HashSet<dictTeamsPlayers>();
            this.TeamsPlayer = new HashSet<TeamsPlayer>();
            this.SinglePlayer = new HashSet<SinglePlayer>();
            this.Teams = new HashSet<Teams>();
        }
    
        public int IdDictTeams { get; set; }
        public int IdCountries { get; set; }
        public int IdDictFormations { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public byte Active { get; set; }
        public Nullable<int> Pressing { get; set; }
        public Nullable<int> AttackLevel { get; set; }
        public Nullable<int> Aggression { get; set; }
    
        public virtual dictCountries dictCountries { get; set; }
        public virtual dictFormations dictFormations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dictTeamsPlayers> dictTeamsPlayers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamsPlayer> TeamsPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinglePlayer> SinglePlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teams> Teams { get; set; }
    }
}
