//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinglePlayer
    {
        public int IdSinglePlayer { get; set; }
        public int IdUser { get; set; }
        public int IdTeam { get; set; }
        public int Season { get; set; }
        public int Week { get; set; }
        public int Day { get; set; }
        public System.DateTime StartDate { get; set; }
        public byte Active { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int FirstMatchDay { get; set; }
        public int NumberOfRestDays { get; set; }
    
        public virtual dictTeams dictTeams { get; set; }
        public virtual Users Users { get; set; }
    }
}
