//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartParameters
    {
        public int IdStartParameters { get; set; }
        public int SeasonNumber { get; set; }
        public int YearStart { get; set; }
        public int MonthStart { get; set; }
        public int WeekStart { get; set; }
        public int DayStart { get; set; }
        public int FirstMatchDayStart { get; set; }
        public int NumberOfRestDays { get; set; }
    }
}
