//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teams()
        {
            this.SinglePlayer = new HashSet<SinglePlayer>();
        }
    
        public int IdTeam { get; set; }
        public int IdDictTeams { get; set; }
        public int IdCountries { get; set; }
        public int IdDictFormations { get; set; }
        public int IdUser { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public int Pressing { get; set; }
        public int AttackLevel { get; set; }
        public int Aggression { get; set; }
        public Nullable<int> Played { get; set; }
        public Nullable<int> Win { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> GoalsFor { get; set; }
        public Nullable<int> GoalsAgainst { get; set; }
        public Nullable<int> Points { get; set; }
        public byte Active { get; set; }
    
        public virtual dictCountries dictCountries { get; set; }
        public virtual dictFormations dictFormations { get; set; }
        public virtual dictTeams dictTeams { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinglePlayer> SinglePlayer { get; set; }
    }
}
