//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsPlayer
    {
        public int IdTeamsPlayers { get; set; }
        public int IdDictTeamsPlayers { get; set; }
        public int IdDictTeams { get; set; }
        public int IdDictCountries { get; set; }
        public int IdDictPositions { get; set; }
        public int IdDictPersons { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int LeftFootSkills { get; set; }
        public int RightFootSkills { get; set; }
        public decimal GoalKeeper { get; set; }
        public decimal Defence { get; set; }
        public decimal Midfield { get; set; }
        public decimal Attack { get; set; }
        public decimal Diving { get; set; }
        public decimal Handling { get; set; }
        public decimal Tackling { get; set; }
        public decimal Covering { get; set; }
        public decimal LongPassAccuracy { get; set; }
        public decimal ShortPassAccuracy { get; set; }
        public decimal ShotAccuracy { get; set; }
        public decimal Speed { get; set; }
        public decimal Acceleration { get; set; }
        public decimal Reflex { get; set; }
        public decimal Heading { get; set; }
        public decimal ShotPower { get; set; }
        public decimal Technique { get; set; }
        public decimal Endurance { get; set; }
        public decimal Stamina { get; set; }
        public decimal AverageSkills { get; set; }
        public decimal AverageDynamicSkills { get; set; }
        public byte Active { get; set; }
    
        public virtual dictCountries dictCountries { get; set; }
        public virtual dictPersons dictPersons { get; set; }
        public virtual dictPositions dictPositions { get; set; }
        public virtual dictTeams dictTeams { get; set; }
        public virtual dictTeamsPlayers dictTeamsPlayers { get; set; }
    }
}
